- name: install kubectl
  yum:
    name: "kubectl-{{ kube_version }}"
    state: present
    allow_downgrade: yes
- name: "Add kubelet config file"
  tags: kubeletWA
  copy:
    src: kubeadm-kubelet.yaml
    dest: /root/kubeadm-kubelet.yaml

