- name: install kubelet
  yum:
    name: "kubelet-{{ kube_version }}"
    state: present
    update_cache: true

- name: install kubeadm
  yum:
    name: "kubeadm-{{ kube_version }}"
    state: present

- name: "Update 10-kubeadm.conf"
  copy:
    src: 10-kubeadm.conf
    dest: /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started
