---
- name: "Get TOKEN"
  shell: "/usr/local/bin/kubeadm token create>/tmp/token.txt"
  register: TOKEN
  tags: join
- name: "Get HASH"
  shell: "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //' >/tmp/hash.txt"
  register: HASH
  tags: join
