---
- name: "Configure new hosts"
  hosts: worker
  tasks:
  - name: "Disable swap,firewalld and configure ip tables"
    include_role:
      name: configure_worker_nodes
      tasks_from: prerequisites
  - name: "Install containerd"
    include_role:
      name: configure_worker_nodes
      tasks_from: install_containerd
  - name: "Install kubelet"
    include_role:
      name: configure_worker_nodes
      tasks_from: install_kubelet
