---
- name: "Configure new hosts"
  hosts: worker
  tasks:
  - name: "Disable swap,firewalld and configure ip tables"
    include_role:
      name: configure_worker_nodes_centos
      tasks_from: prerequisites
  - name: "Install containerd"
    include_role:
      name: configure_worker_nodes_centos
      tasks_from: install_containerd
  - name: "Install kubelet"
    include_role:
      name: configure_worker_nodes_centos
      tasks_from: install_kubelet


- name: "Configure new hosts"
  hosts: master
  tasks:
  - name: "Join to master"
    include_role:
      name: configure_worker_nodes_centos
      tasks_from: join_to_master
    tags:
      - join

- name: "Print Hash and token"
  hosts: worker
  tasks:
    - name: "Get hash and token"
      set_fact:
        TOKEN: "{{ lookup('file','/tmp/token.txt') }}"
        HASH: "{{ lookup('file','/tmp/hash.txt') }}"
        ADVERTISE_URL: "{{ lookup('file','/tmp/advertise.txt').strip().replace(u'\u001b[0m',"") }}"
      tags:
        - join
    - name: "Print facts"
      debug:
        msg: "TOKEN - {{ TOKEN }} ,HASH - {{ HASH }} ,ADVERTISE_URL - {{ ADVERTISE_URL }}"
      tags:
        - join
    - name: "Join Worker node"
      shell: "kubeadm join --discovery-token {{ TOKEN }} --discovery-token-ca-cert-hash sha256:{{ HASH }} {{ ADVERTISE_URL }}"
      tags:
        - join