---
- name: "Install Docker Kubernetes on CentOS "
  hosts: all
  become: true
  tasks:
    - name: "Install Docker"
      include_role:
        name: install_kube
        tasks_from: install_docker.yaml
    - name: "Prerequisites to install kubernetes"
      include_role:
        name: install_kube
        tasks_from: prerequisites.yaml
    - name: "Install kube binaries"
      include_role:
        name: install_kube
        tasks_from: install_kube_common_binaries.yaml

- name: "Install Docker Kubernetes on CentOS "
  hosts: workers
  become: true
  tasks:
    - name: "Install Docker"
      include_role:
        name: install_kube
        tasks_from: install_docker.yaml
    - name: "Prerequisites to install kubernetes"
      include_role:
        name: install_kube
        tasks_from: prerequisites.yaml
    - name: "Install kube binaries"
      include_role:
        name: install_kube
        tasks_from: install_kube_common_binaries.yaml
