---
- name: "Install Kubernetes on master node"
  hosts: master
  tasks:
  #Check if port 6443 is occupied
  - name: Check if required ports are open
    wait_for:
      host: "{{ item.name }}"
      port: "{{ item.port }}"
      state: absent         # Port is not occupied
      delay: 0               # No wait before first check (sec)
      timeout: 3             # Stop checking after timeout (sec)
    ignore_errors: yes
    with_items:
      - name: "master"
        port: 6443 #Kubernetes API server
      - name: "master"
        port: 2379 #etcd server client API
      - name: "master"
        port: 2380 #etcd server client API
      - name: "master"
        port: 10250 #Kubelet API on master
      - name: "worker"
        port: 10250 #Kubelet API on worker
      - name: "master"
        port: 10259 #kube-scheduler
      - name: "master"
        port: 10257 #kube-controller-manager
  - name: "Remove older versions of container runtimes"
    apt:
      name: "{{ items }}"
      state: absent
    with_items:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc