---
- name: "Install Kubernetes on master node"
  hosts: master
  tasks:
  #Check if port 6443 is occupied
  - name: Check if required ports are open
    wait_for:
      host: "{{ item.name }}"
      port: "{{ item.port }}"
      state: absent         # Port is not occupied
      delay: 0               # No wait before first check (sec)
      timeout: 3             # Stop checking after timeout (sec)
    ignore_errors: yes
    with_items:
      - name: "127.0.0.1"
        port: 6443
      - name: "127.0.0.1"
        port: 2379
      - name: "127.0.0.1"
        port: 2380
      - name: "127.0.0.1"
        port: 10250
      - name: "127.0.0.1"
        port: 10259
      - name: "127.0.0.1"
        port: 10257